name: Build Android APK

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd mobile-app
        npm ci
        
    - name: Setup EAS CLI
      run: |
        cd mobile-app
        npm install -g @expo/cli eas-cli
        
    - name: Login to EAS
      run: |
        cd mobile-app
        eas login
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build Android APK (Development Build)
      run: |
        cd mobile-app
        eas build --platform android --profile development --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: smart-farm-app-apk
        path: mobile-app/*.apk