name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # 수동 실행 가능

jobs:
  web-admin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web-admin
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            apps/web-admin/pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build (Next.js)
        run: pnpm build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: apps/web-admin
          scope: ${{ secrets.VERCEL_SCOPE }}

  android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android          # ← 루트/android 로 고정
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest" >/dev/null

      - name: Ensure gradlew exists
        run: |
          ls -la .
          test -f gradlew || (echo "❌ gradlew missing. Commit wrapper files in android/ !" && exit 1)
          chmod +x gradlew

      - name: Build Debug APK
        run: |
          ./gradlew clean assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-farm-app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk